I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 7, in script
    define narattor = character("")
  File "game/script.rpy", line 7, in <module>
    define narattor = character("")
NameError: name 'character' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 7, in script
    define narattor = character("")
  File "/home/aldo3241/renpy/renpy-8.2.3-sdk/renpy/ast.py", line 2222, in execute
    self.set()
  File "/home/aldo3241/renpy/renpy-8.2.3-sdk/renpy/ast.py", line 2236, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/home/aldo3241/renpy/renpy-8.2.3-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 7, in <module>
    define narattor = character("")
NameError: name 'character' is not defined

Linux-6.10.2-arch1-1-x86_64-with-glibc2.40 x86_64
Ren'Py 8.2.3.24061702
HOLLOW 
Sun Aug  4 09:08:30 2024
